### ISSUE TITLE
[v1 (preview 4)] Error creating seed: C5598197

### ISSUE THREAD

**Issue by Dessyreqt** [Dessyreqt/alttprandomizer#16]
Submitter: Dessyreqt
[v1 (preview 4)]

AlttpRandomizer.Random.RandomizationException: Error creating seed: C5598197 ---> System.ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection.
Parameter name: index
   at System.ThrowHelper.ThrowArgumentOutOfRangeException(ExceptionArgument argument, ExceptionResource resource)
   at System.Collections.Generic.List`1.get_Item(Int32 index)
   at AlttpRandomizer.Rom.RomLocationsCasual.GetInsertedLocation(List`1 currentLocations, ItemType insertedItem, SeedRandom random) in D:\Dropbox\Source\alttprandomizer\AlttpRandomizer\Rom\RomLocationsCasual.cs:line 2268
   at AlttpRandomizer.Random.Randomizer.GenerateItemPositions() in D:\Dropbox\Source\alttprandomizer\AlttpRandomizer\Random\Randomizer.cs:line 437
   at AlttpRandomizer.Random.Randomizer.CreateRom(String filename) in D:\Dropbox\Source\alttprandomizer\AlttpRandomizer\Random\Randomizer.cs:line 48
   --- End of inner exception stack trace ---
   at AlttpRandomizer.Random.Randomizer.CreateRom(String filename) in D:\Dropbox\Source\alttprandomizer\AlttpRandomizer\Random\Randomizer.cs:line 55
   at AlttpRandomizer.MainForm.create_Click(Object sender, EventArgs e) in D:\Dropbox\Source\alttprandomizer\AlttpRandomizer\MainForm.cs:line 97

**Comment by Dessyreqt** [comment]
This was an error with Power Glove generation and should be fixed.
